apiVersion: v1
kind: Service
metadata:
    name: eureka-service
    labels:
        type: crm-portal
spec:
    type: NodePort
    ports:
        - targetPort: 8761
          port: 8761
          nodePort: 30011
    selector:
        app: eureka
    