
pipeline {
    agent any
    environment{
        
    }
    stages{
        stage('Pull Code from Source System .....'){
            steps{
                sh "echo pull" 
                
                sh "echo pull" 
            }
        }
        stage('Build Code'){
            steps{
                sh "echo Build"
                
            }
        }
        stage('Build Docker image'){
            steps{
                sh "echo Build Docker image"
            }
        }
        
        stage('Push Docker image to docker hub'){
            steps{
                sh "echo ush Docker image to docker hub"
                
            }
        }
        
    }
}
