
pipeline {
    agent any
    
    tools{
    maven 'Maven-3.6.3'
    }
    environment {
    registry = 'sks007/ems-eureka-server'
    registryCredential = 'dockerhub'
    dockerImage=''
  }
    
    stages{
    	stage('Pull code from git'){
            steps{
               git 'https://github.com/tosahu/EMSEurekaServer.git'  
            }
        }
        stage('Build Code'){
            steps{
                // Run Maven on a Unix agent.  
            sh "mvn -f EMSEurekaServer/pom.xml -Dmaven.test.failure.ignore=true package"

            // To run Maven on a Windows agent, use
            // bat "mvn -Dmaven.test.failure.ignore=true package"
            }
        }
        stage('Build Docker image'){
            steps{
                sh "echo Build Docker image"
                sh "$PWD"
               dir('EMSEurekaServer'){
            	sh "$PWD"
            	sh "docker build -t sks007/ems-eureka-server ."
          }
          sh "$PWD"
                
                
            }
        }
        
        stage('Push Docker image to docker hub'){
            steps{
                sh "echo ush Docker image to docker hub"
                sh "docker push sks007/ems-eureka-server"
            }
        }
        
    }
}
