
pipeline {
    agent any
    
    tools{
    maven 'Maven-3.6.3'
    }
    environment {
    registry = 'sks007/ems-eureka-server'
    registryCredential = 'dockerhub'
    dockerImage=''
  }
    
    stages{
    	stage('Pull code from git'){
            steps{
               git 'https://github.com/tosahu/EMSEurekaServer.git'  
            }
        }
        stage('Build Code'){
            steps{
                // Run Maven on a Unix agent.  
            sh "mvn -f EMSEurekaServer/pom.xml -Dmaven.test.failure.ignore=true package"

            // To run Maven on a Windows agent, use
            // bat "mvn -Dmaven.test.failure.ignore=true package"
            }
        }
        stage('Build Docker image'){
            steps{
                sh "echo Build Docker image"
                sh "pwd"
               dir('EMSEurekaServer'){
            	sh "pwd"
            	sh "docker build -t sks007/ems-eureka-server ."
          }
          sh "pwd"
                
                
            }
        }
        
        stage('Push Docker image to docker hub'){
            steps{
                sh "echo ush Docker image to docker hub"
                sh "docker push sks007/ems-eureka-server"
            }
        }
        
        stage('Deploy to Kubernetes'){
        	steps{
        		dir('EMSEurekaServer'){
        		  
        		  sshagent(['kubernetes-client']) {
        		  script{
            		sh "scp -o StrictHostKeyChecking=no deployment_definition_eureka.yaml,eureka_service_definition.yaml ubuntu@35.154.30.89:/home/ubuntu/"
	   				try{
	   					  sh "ssh ubuntu@35.154.30.89 kubectl create -f /home/ubuntu/deployment_definition_eureka.yaml"
	   				}catch(ex){
	     				sh "ssh ubuntu@35.154.30.89 kubectl apply -f /home/ubuntu/deployment_definition_eureka.yaml"
	  				 }
	  				 sh "ssh ubuntu@35.154.30.89 kubectl create -f /home/ubuntu/eureka_service_definition.yaml"
	  				}
        	}
         
        		  
        		  
	  			 }
			
		}
   }
    }
}
